from eth_utils import denoms

GAS_EXTCODEHASH_STRETCH = 400
GAS_SSTORE_STRETCH_NOOP = 200
GAS_SSTORE_STRETCH_INIT = 20000
GAS_SSTORE_STRETCH_CLEAN = 5000
GAS_SSTORE_STRETCH_CLEAR_REFUND = 15000
GAS_SSTORE_STRETCH_RESET_CLEAR_REFUND = 19800
GAS_SSTORE_STRETCH_RESET_REFUND = 4800

STRETCH_BLOCK_REWARD = 2 * denoms.ether
